<h1 id="" style="color:">Integritetspolicy</h1>

<span class="ArticleBody"><P>Ditt besök på Motiomera står under nedanstående villkor.</P>
<H2>Om denna Integritetspolicy</H2>
Motiomera&nbsp;följer alla de lagar och regler, inklusive personuppgiftslagen (1998:204) (PUL), som finns för att skydda privatpersoners integritet. Om du registrerar dig till tjänsten lagras dina personuppgifter för att vi skall kunna tillgodose tjänsten. Läs mer detaljerad information nedan under stycket Personuppgifter.<BR>När du besöker Motiomera och/eller när du laddar ned sidor via en webbläsare eller når våra webbsidor via e-mailklient registreras dina besök via s.k. cookies. Sådan information används bland annat till att ge information om antalet besökare och vilka webbsidor på webbplatsen som besöks. Läs mer detaljerad information nedan under stycket Om Cookies.</P>

<H2>Om Cookies</H2>
<P>Motiomera använder s.k. cookies. En cookie är en liten textfil som skickas från vår server till din webbläsare. Cookien kan inte identifiera dig personligen utan endast den webbläsare som finns installerad på din dator och som du använder vid besöket. Olika cookies finns alltså på olika datorer för det fall du använder olika datorer för att nå vår webbplats. Motiomera behöver cookies för att fungera säkert och korrekt. Exempelvis för att logga in på ett användarkonto.<BR>Det finns två sorters cookies, den ena typen kallas sessioncookies och den andra kallas permanent cookie. En sessioncookie skickas mellan din dator och vår server för att webbsidorna ska fungera korrekt under ditt besök. En sessionscookie lagras inte på din dator, utan försvinner när du stänger din webbläsare. En permanent cookie lagras däremot i din dator och gör till exempel så att vår webbsida kan känna igen din dators IP-adress och därmed din webbläsare nästa gång du loggar in.<BR>Motiomera använder både sessioncookies och permanenta cookies.<BR>Du kan avstå ifrån att låta Motiomera lagra cookies i din dator genom att göra en inställning i din webbläsare men du kan då inte längre använda webbsidorna, av funktionella skäl.</P>
<H2>Copyright och Varumärken</H2>
<P>För allt innehåll på vår sajt gäller copyright Motiomera. Detta innebär att allt innehåll i form av exempelvis olika typer av texter, filmer, artiklar, reportage, ljudslingor, radio, varumärken, grafik och illustrationer är bland annat rättsligt skyddade enligt lag (1960:729) om upphovsrätt och av varumärkeslag (1960:644) om inget annat anges. <BR>Det material som publiceras via Motiomera är Motiomera egendom alternativt egendom tillhörande tredje man med vilken Motiomera samarbetar och får inte användas av dig utöver vad som krävs för webbsidornas nyttjande enligt gällande villkor. Du äger således inte rätt att kopiera, sprida, skicka vidare eller på annat sätt göra material tillgängligt utan Motiomera skriftliga medgivande.<BR>Motiomera förbehåller sig rätten att, utan begränsning till tid, använda och publicera inskickat material till webbsidorna från dess besökare (så kallat användargenererat innehåll beskrivet nedan) till exempel bilder, textkommentarer och liknande.</P>
<H2>Användargenererat Innehåll och Nätetikett</H2>
<P>Med användargenererat innehåll avses allt sådant innehåll som webbplatsens besökare skapar eller laddar upp till webbplatsen. Dvs. allt innehåll som ej är skapat av Motiomera. Exempelvis är uppladdade bilder och text i form av kommentarer till artiklar användargenererat innehåll. <BR>När du använder funktionalitet på Motiomera webbplats där användargenererat innehåll kan skapas såsom forum, kommentarer till bloggar, etc. medverkar du som privatperson direkt med innehåll som du själv ansvarar för och som du som användare av webbplatsen kan ställas till svars för. För detta innehåll gäller inte det utgivaransvar som i övrigt gäller på Motiomera. Du har inget meddelarskydd och vi kan inte garantera din anonymitet även om vi i så hög grad som möjligt försöker säkerställa den.<BR>Användargenererat innehåll får under inga omständigheter innehålla: <BR>- Hets mot folkgrupp eller annat innehåll av rasistisk eller stötande karaktär. <BR>- Kränkande uppgifter såsom förtal eller förolämpning, hot, personliga påhopp eller stötande uppgifter.<BR>- Uppmaning till brottslig handling.<BR>- Olaga våldsskildring, pornografi eller barnpornografi.<BR>- Uppgifter som utgör upphovsrättsintrång. <BR>- Spridning av datavirus och massutskick, s.k. spam.<BR>- Programkod som kan vara skadlig och påverka webbplatsens funktionalitet på något sätt.<BR>- Erbjudanden om sexuella tjänster, enkäter, egna tävlingar, direktreklam, massutskick, privata annonser eller liknande.<BR>Är du som användare av Motiomera det minsta tveksam kring innebörden av ovan, vänligen avstå från att bidra med innehåll. <BR>Motiomera har rätt, men inte skyldighet, att omedelbart, helt eller delvis, avlägsna eller inte vidarebefordra användargenererat innehåll som strider helt eller delvis mot dessa villkor. För det fall sådant missbruk ändå skulle uppkomma äger Motiomera rätt att vidtaga de åtgärder som är nödvändiga för att förhindra missbruket. Sådana åtgärder kan bl.a. innefatta att stänga av eller vidtaga begränsningar för dig som användare eller medlem. Vid mer allvarliga överträdelser kan även rättsliga åtgärder komma att aktualiseras, vilket Motiomera – om så är möjligt – i sådana fall meddelar att man har för avsikt att vidtaga sådana åtgärder.<BR>Se stycket Copyright och Varumärken kring rättigheter för användargenererat innehåll.</P>

<H2>Medlemsuppgifter vid registrering</H2>
<P>I de fall funktionalitet på webbplatsen förutsätter registrering, är det av största vikt att du ej lämnar ut ditt användarnamn och lösenord till obehörig samt vid alla tillfällen kontrollerar så att obehörig ej kan använda sig av de uppgifter du angivit i din registrering i syfte att utge sig för att vara du. Detta eftersom du som användare är personligt ansvarig för allt som skrivs och beställs från den registrering du skapar. Glöm därför inte att logga ut när du lämnar datorn och var aktsam om du exempelvis använder autoinloggning. <BR>Motiomera förbehåller sig rätten att neka till samt att ta bort olämpliga och stötande användarnamn. <BR>I de fall funktionalitet sker i samarbete med externa leverantörer kan det i dessa fall innebära att tidigare registrerade uppgifter för Motiomera ej kan användas. Då gäller samarbetspartnerns medlemsrutiner. Med funktionalitet som sker i samarbete med externa leverantörer kan följande avses, men även andra former av samarbeten, - tekniska eller kommersiella, som rör hur webbplatsernas tjänster fungerar: Syndikering av programkod via RSS ("RDF Site Summary" eller "Really Simple Syndication"), XML ("Extensible Markup Language", s.k. iFrames eller liknande s.k. web feeds som gör att innehåll eller tjänster hos en extern leverantör presenteras integrerat via webbplats från Motiomera, s.k. Syndikering av innehåll."</P>
<H2>Personuppgifter</H2>
<P>Motiomera följer alla de lagar och regler, inklusive personuppgiftslagen (1998:204) (PUL), som finns för att skydda privatpersoners integritet. Genom att du registrerar dig på Motiomeras webbplats eller via annan kommunikationskanal registrerar dina personuppgifter, ger du samtidigt ditt samtycke härtill, att dina uppgifter behandlas såsom beskrivet under denna rubrik.<BR>Motiomeras medlemsregister med personuppgifter, inhämtade från webbplatsen eller på annat sätt, är konfidentiella. Den information du som användare av webbplatserna gett oss, såsom kontaktuppgifter och övriga personuppgifter, kommer inte att användas på annat sätt än för att ge dig tillgång till information och tjänster eller från tredje part godkänd av Motiomera. <BR>För att ändra dina uppgifter, kontakta Motiomera på följande e-postadress <A href="mailto:noreply@motiomera.se" orgurl="mailto:noreply@motiomera.se">noreply@motiomera.se</A> <BR>Vi använder dina personuppgifter för att fullgöra åtaganden, hantera prenumerationer, kundrelationer, marknadsföring och direktmarknadsföring postalt som digitalt. Komplettering genom inhämtning från och samkörning med andra privata och offentliga register (exempelvis SPAR) vid t ex uppdatering av adressuppgifter kan komma att ske. <BR>Personuppgifterna kan komma att lämnas ut till andra företag eller partners godkända av Motiomera för nödvändig behandling på uppdrag av Motiomera, t ex i samband med tryck och distribution eller för marknadsföring. Vid misstanke om brott lämnas personuppgifter ut till polis och andra relevanta myndigheter. Dina personuppgifter vidarebefordras aldrig utan sekretessavtal. Dina personuppgifter behandlas med modern informationsteknik och informationskanaler.</P>

<H2>Borttagande av medlemsuppgifter</H2>
<P>Som användare av Motiomera kan du som användare när som helst återkalla lämnat samtycke. Du kan göra detta genom att&nbsp;kontakta Motiomera på följande e-postadress <A href="mailto:noreply@motiomera.se" orgurl="mailto:noreply@motiomera.se">noreply@motiomera.se</A></P>
<H2>Ansvarsfriskrivning</H2>
<P>Motiomera kan inte göras ansvariga för skador som direkt eller indirekt eventuellt orsakas av att du som användare använder våra webbplatser. Motiomera lämnar inga garantier gällande tillgänglighet eller funktion.<BR>Motiomera kan inte göras ansvariga för lagligheten i innehållet på de webbsidor vi länkar till från vår webbplats. Vi kan heller inte garantera att publicerade länkar fungerar.<BR>Motiomera kan ej heller göras ansvarig för någon slags förlust som är relaterad till din användning av innehållet på webbplatsen. Denna ansvarsfriskrivning omfattar såväl direkta som indirekta förluster och inkluderar förluster som orsakas av driftstörningar, att webbplatsen ej är tillgänglig och liknande.<BR>Motiomera fråntar sig ansvaret för medlemsregistret i händelse av; sabotage/dataintrång eller annan yttre påverkan som ligger utanför vår kontroll eller händelse som är att betrakta som force majeure.<BR>Motiomeras webbplats vänder sig till den svenska marknaden och skall följaktligen bedömas enligt svensk lag. De eventuella användare utanför Sveriges gräns är själva ansvariga för att de regler, lagar och förordningar som finns där för var tid efterföljs.&nbsp;&nbsp; </P></span>