USE `motiomera`;
DROP TABLE `mm_kommunbak`;
DROP TABLE `mm_quizalternativ_kopia`;
DROP TABLE `mm_quizfraga_kopia`;
DROP TABLE `mm_test`;
DROP TABLE `mm_test2`;
ALTER TABLE `mm_admin` DROP `serialize`;
ALTER TABLE `mm_aktivitet` DROP `serialize`;
ALTER TABLE `mm_anslagstavla` DROP `serialize`;
ALTER TABLE `mm_anslagstavlarad` DROP `serialize`;
ALTER TABLE `mm_feeditem` DROP `serialize`;
ALTER TABLE `mm_foretag` DROP `serialize`;
ALTER TABLE `mm_fotoalbum` DROP `serialize`;
ALTER TABLE `mm_fotoalbumbild` DROP `serialize`;
ALTER TABLE `mm_grupp` DROP `serialize`;
ALTER TABLE `mm_help` DROP `serialize`;
ALTER TABLE `mm_kommun` DROP `serialize`;
ALTER TABLE `mm_kommunbild` DROP `serialize`;
ALTER TABLE `mm_lag` DROP `serialize`;
ALTER TABLE `mm_lagnamn` DROP `serialize`;
ALTER TABLE `mm_mal` DROP `serialize`;
ALTER TABLE `mm_medlem` DROP `serialize`;
ALTER TABLE `mm_motiomeramail` DROP `serialize`;
ALTER TABLE `mm_motiomeramail_folders` DROP `serialize`;
ALTER TABLE `mm_order` DROP `serialize`;
ALTER TABLE `mm_profildata` DROP `serialize`;
ALTER TABLE `mm_profildataval` DROP `serialize`;
ALTER TABLE `mm_quizalternativ` DROP `serialize`;
ALTER TABLE `mm_quizfraga` DROP `serialize`;
ALTER TABLE `mm_quizsuccess` DROP `serialize`;
ALTER TABLE `mm_steg` DROP `serialize`;
ALTER TABLE `mm_stracka` DROP `serialize`;
ALTER TABLE `mm_texteditor` DROP `serialize`;