use `motiomera` ;

drop TABLE `mm_aktivitet` ;

CREATE TABLE IF NOT EXISTS `mm_aktivitet` (
  `id` int(10) unsigned NOT NULL auto_increment,
  `namn` varchar(255) collate utf8_swedish_ci NOT NULL,
  `enhet` varchar(32) collate utf8_swedish_ci NOT NULL,
  `varde` int(11) NOT NULL,
  `beskrivning` varchar(255) collate utf8_swedish_ci NOT NULL,
  `borttagen` enum('ja','nej') collate utf8_swedish_ci NOT NULL default 'nej',
  `svarighetsgrad` varchar(155) collate utf8_swedish_ci NOT NULL,
  PRIMARY KEY  (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 COLLATE=utf8_swedish_ci AUTO_INCREMENT=119 ;

--
-- Dumping data for table `mm_aktivitet`
--

INSERT INTO `mm_aktivitet` (`id`, `namn`, `enhet`, `varde`, `beskrivning`, `borttagen`, `svarighetsgrad`) VALUES
(2, 'Boxning', 'minuter', 80, '...', 'nej', ''),
(3, 'Styrketräning', 'minuter', 120, '...', 'ja', ''),
(4, 'Aerobics', 'minuter', 50, '', 'ja', ''),
(5, 'Steg', 'steg', 1, '', 'nej', ''),
(13, 'Badminton', 'minuter', 100, '', 'nej', 'lätt'),
(12, 'Aerobics', 'minuter', 100, '', 'nej', 'lätt'),
(14, 'Aerobics', 'minuter', 140, '', 'nej', 'medel'),
(15, 'Aerobics', 'minuter', 180, '', 'nej', 'tuff'),
(16, 'Badminton', 'minuter', 140, '', 'nej', 'medel'),
(17, 'Badminton', 'minuter', 180, '', 'nej', 'tuff'),
(18, 'Basket', 'minuter', 140, '', 'nej', ''),
(19, 'Beachvolleyboll', 'minuter', 160, '', 'nej', ''),
(20, 'BodyBalance', 'minuter', 100, '', 'nej', ''),
(21, 'BodyPump', 'minuter', 170, '', 'nej', ''),
(22, 'Bordtennis', 'minuter', 70, '', 'nej', 'lätt'),
(23, 'Bordtennis', 'minuter', 100, '', 'nej', 'medel'),
(24, 'Bordtennis', 'minuter', 130, '', 'nej', 'tuff'),
(25, 'Bowling', 'minuter', 70, '', 'nej', ''),
(26, 'Boxercise', 'minuter', 130, '', 'nej', 'lätt'),
(27, 'Boxercise', 'minuter', 170, '', 'nej', 'medel'),
(28, 'Boxercise', 'minuter', 200, '', 'nej', 'tuff'),
(29, 'Brottning', 'minuter', 160, '', 'nej', ''),
(30, 'Cirkelträning', 'minuter', 130, '', 'nej', 'lätt'),
(31, 'Cirkelträning', 'minuter', 170, '', 'nej', 'medel'),
(32, 'Cirkelträning', 'minuter', 210, '', 'nej', 'tuff'),
(33, 'Coreträning', 'minuter', 110, '', 'nej', ''),
(34, 'Crosstrainer', 'minuter', 110, '', 'nej', 'lätt'),
(35, 'Crosstrainer', 'minuter', 150, '', 'nej', 'medel'),
(36, 'Crosstrainer', 'minuter', 210, '', 'nej', 'tuff'),
(37, 'Cykling', 'minuter', 80, '', 'nej', 'lätt'),
(38, 'Cykling', 'minuter', 130, '', 'nej', 'medel'),
(39, 'Cykling', 'minuter', 220, '', 'nej', 'tuff'),
(40, 'Dans', 'minuter', 70, '', 'nej', 'lätt'),
(41, 'Dans', 'minuter', 130, '', 'nej', 'medel'),
(42, 'Dans', 'minuter', 180, '', 'nej', 'tuff'),
(43, 'Fotboll', 'minuter', 160, '', 'nej', ''),
(44, 'Golf', 'minuter', 90, '', 'nej', ''),
(45, 'Gympa', 'minuter', 100, '', 'nej', 'lätt'),
(46, 'Gympa', 'minuter', 140, '', 'nej', 'medel'),
(47, 'Gympa', 'minuter', 180, '', 'nej', 'tuff'),
(48, 'Gå uppför trappor', 'minuter', 210, '', 'nej', 'intensivt'),
(49, 'Handboll', 'minuter', 160, '', 'nej', ''),
(50, 'Hoppa rep', 'minuter', 120, '', 'nej', 'lätt'),
(51, 'Hoppa rep', 'minuter', 170, '', 'nej', 'medel'),
(52, 'Hoppa rep', 'minuter', 220, '', 'nej', 'tuff'),
(53, 'Hoppa studsmatta', 'minuter', 80, '', 'nej', 'lätt'),
(54, 'Hoppa studsmatta', 'minuter', 140, '', 'nej', 'medel'),
(55, 'Hoppa studsmatta', 'minuter', 210, '', 'nej', 'tuff'),
(56, 'Inlines', 'minuter', 100, '', 'nej', 'lätt'),
(57, 'Inlines', 'minuter', 160, '', 'nej', 'medel'),
(58, 'Inlines', 'minuter', 220, '', 'nej', 'tuff'),
(59, 'Innebandy', 'minuter', 160, '', 'nej', ''),
(60, 'Ishockey', 'minuter', 170, '', 'nej', ''),
(61, 'Joggning', 'minuter', 160, '', 'nej', 'lätt'),
(62, 'Joggning/löpning', 'minuter', 250, '', 'nej', 'medel'),
(63, 'Joggning/löpning', 'minuter', 300, '', 'nej', 'tuff'),
(64, 'Kampsport', 'minuter', 150, '', 'nej', 'lätt'),
(65, 'Kampsport', 'minuter', 180, '', 'nej', 'medel'),
(66, 'Kampsport', 'minuter', 240, '', 'nej', 'tuff'),
(67, 'Pilates', 'minuter', 100, '', 'nej', ''),
(68, 'Powerwalking', 'minuter', 170, '', 'nej', ''),
(69, 'Promenad', 'minuter', 90, '', 'nej', 'lätt'),
(70, 'Promenad', 'minuter', 110, '', 'nej', 'medel'),
(71, 'Promenad', 'minuter', 140, '', 'nej', 'tuff'),
(72, 'Qigong/taichi', 'minuter', 80, '', 'nej', ''),
(73, 'Ridning', 'minuter', 140, '', 'nej', ''),
(74, 'Rodd/roddmaskin/paddling', 'minuter', 130, '', 'nej', 'lätt'),
(75, 'Rodd/roddmaskin/paddling', 'minuter', 170, '', 'nej', 'medel'),
(76, 'Rodd/roddmaskin/paddling', 'minuter', 220, '', 'nej', 'tuff'),
(77, 'Simning', 'minuter', 130, '', 'nej', 'lätt'),
(78, 'Simning', 'minuter', 170, '', 'nej', 'medel'),
(79, 'Simning', 'minuter', 230, '', 'nej', 'tuff'),
(80, 'Skidor (längd)', 'minuter', 140, '', 'nej', 'lätt'),
(81, 'Skidor (längd)', 'minuter', 180, '', 'nej', 'medel'),
(82, 'Skidor (längd)', 'minuter', 320, '', 'nej', 'tuff'),
(83, 'Skidor (utför)', 'minuter', 90, '', 'nej', 'lätt'),
(84, 'Skidor (utför)', 'minuter', 130, '', 'nej', 'medel'),
(85, 'Skidor (utför)', 'minuter', 170, '', 'nej', 'tuff'),
(86, 'Skridsko', 'minuter', 110, '', 'nej', 'lätt'),
(87, 'Skridsko', 'minuter', 160, '', 'nej', 'medel'),
(88, 'Skridsko', 'minuter', 200, '', 'nej', 'tuff'),
(89, 'Spinning', 'minuter', 120, '', 'nej', 'lätt'),
(90, 'Spinning', 'minuter', 180, '', 'nej', 'medel'),
(91, 'Spinning', 'minuter', 280, '', 'nej', 'tuff'),
(92, 'Squash', 'minuter', 170, '', 'nej', 'lätt'),
(93, 'Squash', 'minuter', 240, '', 'nej', 'medel'),
(94, 'Squash', 'minuter', 280, '', 'nej', 'tuff'),
(95, 'Stavgång', 'minuter', 120, '', 'nej', 'lätt'),
(96, 'Stavgång', 'minuter', 150, '', 'nej', 'medel'),
(97, 'Stavgång', 'minuter', 190, '', 'nej', 'tuff'),
(98, 'Step up', 'minuter', 130, '', 'nej', 'lätt'),
(99, 'Step up', 'minuter', 170, '', 'nej', 'medel'),
(100, 'Step up', 'minuter', 200, '', 'nej', 'tuff'),
(101, 'Stepmaskin/trappmaskin', 'minuter', 100, '', 'nej', 'lätt'),
(102, 'Stepmaskin/trappmaskin', 'minuter', 140, '', 'nej', 'medel'),
(103, 'Stepmaskin/trappmaskin', 'minuter', 170, '', 'nej', 'tuff'),
(104, 'Stretching', 'minuter', 60, '', 'nej', ''),
(105, 'Styrketräning', 'minuter', 80, '', 'nej', 'lätt'),
(106, 'Styrketräning', 'minuter', 110, '', 'nej', 'medel'),
(107, 'Styrketräning', 'minuter', 170, '', 'nej', 'tuff'),
(108, 'Tennis', 'minuter', 100, '', 'nej', 'lätt'),
(109, 'Tennis', 'minuter', 140, '', 'nej', 'medel'),
(110, 'Tennis', 'minuter', 180, '', 'nej', 'tuff'),
(111, 'Vandring med tung ryggsäck (10-15 kg)', 'minuter', 190, '', 'nej', ''),
(112, 'Vattengympa', 'minuter', 80, '', 'nej', 'lätt'),
(113, 'Vattengympa', 'minuter', 120, '', 'nej', 'medel'),
(114, 'Vattengympa', 'minuter', 140, '', 'nej', 'tuff'),
(115, 'Volleyboll', 'minuter', 100, '', 'nej', ''),
(116, 'Yoga, (t ex iyengaryoga) ', 'minuter', 60, '', 'nej', 'lätt'),
(117, 'Yoga, (t ex kundaliniyoga) ', 'minuter', 80, '', 'nej', 'medel'),
(118, 'Yoga, (t ex poweryoga, ashtangayoga) ', 'minuter', 120, '', 'nej', 'tuff');

